feat: Сервис статистики
VitalyKapustin-git/java-explore-with-me pull request #1
Opened 2023-01-30 21:31 UTC by VitalyKapustin-git

- Добавлена функциональность для сервиса статистики

2023-01-31 23:00 UTC, alexache requested changes

2023-01-31 23:00 UTC, alexache commented on analytics-app/pom.xml
> +            <version>2.7.4</version>
Для чего указывать конкретную версию? Должна быть от spring-boot-starter-parent

2023-01-31 23:00 UTC, alexache commented on analytics-app/pom.xml
> +            <groupId>ru.practicum</groupId>
Для чего эта зависомость?

2023-01-31 23:00 UTC, alexache commented on analytics-app/src/main/java/ru/practicum/core/http/ServletRequestHandler.java
> +        JsonNode root = mapper.readTree(response.getBody());
Для чего такая низкоуровневая работа с JSON объектом? Почему бы полноценно не десериализовать в некую ДТО модель ответа?

2023-01-31 23:00 UTC, alexache commented on analytics-app/src/main/java/ru/practicum/core/http/ServletRequestHandler.java
> +    public void handleHttpReq(HttpServletRequest httpServletRequest) {
Из названия метода не очень очевидно предназначение, а так же httpServlerRequest выглядит не очень хорошим входным аргументом для передачи статистики

2023-01-31 23:00 UTC, alexache commented on analytics-app/src/main/java/ru/practicum/view/ViewController.java
> +        System.out.println("CONTROLLER");
Для чего в консоль? Может полноценно логгер использовать?

2023-01-31 23:00 UTC, alexache commented on analytics-app/src/main/java/ru/practicum/view/ViewServiceImpl.java
> +        System.out.println("SERVICE START");
Почему не логгер?

2023-02-01 21:57 UTC, VitalyKapustin-git commented on analytics-app/src/main/java/ru/practicum/view/ViewServiceImpl.java
> +        System.out.println("SERVICE START");
Дебажил, забыл убрать

2023-02-01 21:57 UTC, VitalyKapustin-git commented on analytics-app/src/main/java/ru/practicum/view/ViewController.java
> +        System.out.println("CONTROLLER");
Дебажил, забыл убрать

2023-02-01 21:57 UTC, VitalyKapustin-git commented on analytics-app/src/main/java/ru/practicum/core/http/ServletRequestHandler.java
> +    public void handleHttpReq(HttpServletRequest httpServletRequest) {
Поработал над неймингами

2023-02-01 21:58 UTC, VitalyKapustin-git commented on analytics-app/src/main/java/ru/practicum/core/http/ServletRequestHandler.java
> +        JsonNode root = mapper.readTree(response.getBody());
Десериализовал

2023-02-01 21:59 UTC, VitalyKapustin-git commented on analytics-app/pom.xml
> +            <groupId>ru.practicum</groupId>
Артефакт оставшийся после написания основного сервиса и аналитики. Пока переделывал под новые требования видимо затерялось

2023-02-01 22:01 UTC, VitalyKapustin-git commented on analytics-app/pom.xml
> +            <version>2.7.4</version>
Поправил

2023-02-02 21:49 UTC, alexache approved these changes

2023-02-06 16:16 UTC, merged