main service feature
VitalyKapustin-git/java-explore-with-me pull request #2
Opened 2023-02-10 18:59 UTC by VitalyKapustin-git

- feat: реализован основной сервис;

2023-02-13 10:52 UTC, alexache requested changes

2023-02-13 10:52 UTC, alexache commented on afisha-app/pom.xml
> +            <version>2.7.4</version>
Нужно ли указывать эту версию?
В родительском модуле есть использование spring-boot-starter-parent
Если конкретно этой версии не будет в спринг родительском, то версии должны быть указаны только в родительском модуле через dependencyManagement

2023-02-13 10:52 UTC, alexache commented on afisha-app/pom.xml
> +                <version>3.1.2</version>
Тоже касается и плагинов - версии только в родительском модуле

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/category/Category.java
> +package ru.practicum.category;
Не помешает, пожалуй, больше пакетов, чтобы модели, дто были отдельно даже в пакетах сущностей

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +@Primary
Для чего эта аннотация? Есть ли другая реализация сервиса?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +        if (categoryRepository.getCategoryByName(categoryDto.getName()) != null)
Что если при "обновлении" имя не будет изменено, получим эксепшен?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationNewDto.java
> +    private List<Long> events;
Может тут ДТО событий больше подойдут?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationRepository.java
> +    List<Compilation> getCompilationsByPinnedIsTrue(Pageable pageable);
А нельзя написать один метод под эти два случая и передавать pinned, как аргумент?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationServiceImpl.java
> +            compilationRepository.save(compilation);
А если список из событий не меняется, то остальные изменения не будут сохранены вовсе?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationUpdateRequestDto.java
> +    List<Long> events;
Модификаторы доступа полей

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/Event.java
> +    private List<Compilation> compilations;
А для чего эти поля здесь используются?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventRepository.java
> +    @Query("select e from Event e where e.initiator.id = ?1")
(опционально) Такой запрос тоже можно написать через наименование метода

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventState.java
> +    private final String name;
Зачем это поле и методы, если есть стандартные у enum  - valueOf() и toString?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/RequestRepository.java
> +    @Query("select r from Request r where r.requester.id = ?1 and r.event.initiator.id <> ?1")
Зачем использовать Query, если можно обойтись именованиеми методов для таких запросов?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        requestDto.setRequester(userService.getUsers(List.of(userId), 0, 10).get(0));
Как-то немного не логично сначала получать модели из базы, переводить из в дто, а затем немного ниже снова переделывать в модели. Логичнее работать с репозиториями сущностей юезра и событий, чтобы получать модели, а не дто

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        requestDto.setRequester(userService.getUsers(List.of(userId), 0, 10).get(0));
И в целом не понял логику, зачем берется какой-то список юзеров и берется первый из него?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        requestRepository.save(request);
Почему 2 сохранения?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/RequestStatusDto.java
> +    List<Long> requestIds;
Модификаторы доступа?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        List<RequestShortDto> eventRequests = requestRepository
Разве в этом всем методе не меняться только 1 заявка?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/user/User.java
> +//    private List<Request> requests;
Для чего этот закомментированный код?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/user/UserRepository.java
> +    @Query("select u.name from User u where u.name = ?1")
Что этот запрос означает? Получение имени по имени?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/user/UserServiceImpl.java
> +        if (getUsers(List.of(userId), 0, 1).size() == 0)
Странный запрос, почему не просто getUserById?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/user/UserServiceImpl.java
> +        userDto.setId(user.getId());
А айди точно берется из сущности из базы? Разве не стоит брать айди их возвращаемого значения из метода save?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +    private final HttpServletRequest request;
Это очень плохо, что появился какое-то состояние. Сервис не должен иметь полей, связанных с каким-то конкретным запросом

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            eventShortDto.setViews(statsHttpClient.getViews("/events/" + eventShortDto.getId(),
Запрос к сервису статистики довольно плохая затея. лучше иметь 1 запрос по списку событий

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +        eventRepository.save(event);
А получение айди?

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            switch (eventUpdateAdminDto.getStateAction()) {
Странный switch

2023-02-13 10:52 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +        return entityManager.createQuery("" +
Почему не запросом в репозитории? Не очень хорошо смешивать слои

2023-02-13 12:11 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationNewDto.java
> +    private List<Long> events;
@alexache Я здесь отталкивался от официально спецификации которую в основной репе предоставили. Там NewCompilationDto, в нем события - список idшников

2023-02-13 16:47 UTC, VitalyKapustin-git commented on afisha-app/pom.xml
> +            <version>2.7.4</version>
Поправил

2023-02-13 16:47 UTC, VitalyKapustin-git commented on afisha-app/pom.xml
> +                <version>3.1.2</version>
Поправил

2023-02-13 16:49 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +@Primary
Нет. По привычке, чтобы если еще какая то реализация возникла, не было конфликтов. Убрал

2023-02-13 18:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +        if (categoryRepository.getCategoryByName(categoryDto.getName()) != null)
@alexache Вопроса не понял.
Если новое имя не передадут, то исключение с 68й строки.
Если подадут такое же, то исключение с 73й строки, так как такое имя уже существует.

В категории кроме имени менять больше нечего.

2023-02-13 18:21 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/category/Category.java
> +package ru.practicum.category;
Нас учили что можно и разбивать по пакетам и не разбивать.
Для удобства, разделил везде.

2023-02-13 19:08 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +    private final HttpServletRequest request;
Скорректировал

2023-02-13 19:17 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +        eventRepository.save(event);
@alexache Получение где?
Получил на вход данные для нового события. 
Перевел событие из EventNewDto в Event.
Получил из id пользователя реального и подцепил к Event.
Проставил сразу статус ожидание.
Сохранил объект event соответствующего типа, в него же и записался id события.

По итогу вернул полное событие (EventFullDto) из event.

2023-02-13 19:42 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +        return entityManager.createQuery("" +
Переделал

2023-02-13 19:46 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            switch (eventUpdateAdminDto.getStateAction()) {
@alexache Почему? 
На вход приходит команда которая указывает на то, какой статус должен быть новый. Вот я через switch-case и маплю, чтобы не только if'ы написывать.

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationRepository.java
> +    List<Compilation> getCompilationsByPinnedIsTrue(Pageable pageable);
Переделал

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationUpdateRequestDto.java
> +    List<Long> events;
Поправил

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/EventRepository.java
> +    @Query("select e from Event e where e.initiator.id = ?1")
Скорректировал

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/EventState.java
> +    private final String name;
Убрал лишнее

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/RequestRepository.java
> +    @Query("select r from Request r where r.requester.id = ?1 and r.event.initiator.id <> ?1")
@alexache Про какой запрос именно идет речь?
`@Query("select r from Request r where r.requester.id = ?1 and r.event.initiator.id <> ?1")`
Этот? Если да, то как указать на неравенство и передать один аргумент вместо двух?

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/Event.java
> +    private List<Compilation> compilations;
Почему то думал что при manyToMany нужно на обеих сторонах указывать.
Сами поля мне нужны для статичного именования, чтобы в случае изменений не приходилось переименовывать схемы.
Лишнее убрал.

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        requestDto.setRequester(userService.getUsers(List.of(userId), 0, 10).get(0));
Поправил

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        requestDto.setRequester(userService.getUsers(List.of(userId), 0, 10).get(0));
Да, много ненужного. Переделал

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        requestRepository.save(request);
Очепятка. Поправил

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/RequestStatusDto.java
> +    List<Long> requestIds;
Добавил

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/user/User.java
> +//    private List<Request> requests;
Не дочистил

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/user/UserRepository.java
> +    @Query("select u.name from User u where u.name = ?1")
Поправил. Сбился с мысли на тестах постмана, там речь про имя, хотя проверять надо почту.

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/user/UserServiceImpl.java
> +        if (getUsers(List.of(userId), 0, 1).size() == 0)
Поправил

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/user/UserServiceImpl.java
> +        userDto.setId(user.getId());
Берется. Но я все равно подсократил.

2023-02-13 22:20 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            eventShortDto.setViews(statsHttpClient.getViews("/events/" + eventShortDto.getId(),
Да, я знаю что в цикле обращаться так себе, но исходил из представленной спецификации api для сервиса, так как это дипломный проект и постоянно происходят какие то изменения по условиям проверки).

Переделал клиент + обработку ответа от него. Теперь получаю сразу пачку данных и в сервисе просто разбираю.

2023-02-13 22:27 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationServiceImpl.java
> +            compilationRepository.save(compilation);
Поправил

2023-02-13 22:31 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        List<RequestShortDto> eventRequests = requestRepository
Нет. Этот эндпоинт про: Новый статус для заявок на участие в событии текущего пользователя
Т.е. изменение для одной или нескольких (в RequestShortDto лист заявок).

2023-02-13 23:13 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/category/CategoryServiceImpl.java
> +        if (categoryRepository.getCategoryByName(categoryDto.getName()) != null)
Можно считать коммент опциональным. Вот я про второй случай, исключение о том, что такая категория уже есть немного о другом, нежели что имя категории не меняется. Но это вкусовщина, а не строгое требование ТЗ

2023-02-13 23:14 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/compilation/CompilationNewDto.java
> +    private List<Long> events;
Ок, принято. Наверное поменяли с прошлого потока

2023-02-13 23:17 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/RequestRepository.java
> +    @Query("select r from Request r where r.requester.id = ?1 and r.event.initiator.id <> ?1")
Неравенство это not, если я правильно помню, а второй аргумент можно передать такой же как первый, потому что на уверен, что это можно обойти

2023-02-13 23:18 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/RequestServiceImpl.java
> +        List<RequestShortDto> eventRequests = requestRepository
Ок

2023-02-13 23:21 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +        eventRepository.save(event);
Лучше полагаться на возвращаемое значение из save, как по мне
https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html#save(S)

2023-02-13 23:24 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +            switch (eventUpdateAdminDto.getStateAction()) {
Вот сейчас и сам не вспомню, что именно смутило. Может неиспользование enum, но не факт. Можно пропустить

2023-02-14 07:41 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/EventServiceImpl.java
> +        eventRepository.save(event);
Поправил

2023-02-14 07:43 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/RequestRepository.java
> +    @Query("select r from Request r where r.requester.id = ?1 and r.event.initiator.id <> ?1")
Здесь я бы оставил как есть. Некрасиво передавать два раза одно и тоже как то.

2023-02-15 19:33 UTC, alexache requested changes

2023-02-15 19:33 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/enums/EventState.java
> +    public final String name;
 Разве это фикс? Лишнее поле осталось

2023-02-15 19:33 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/model/Event.java
>      private List<Compilation> compilations;
Так а само поле то используется?

2023-02-15 19:33 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                            views.get("/events/" + e.getId()) : views.get("/events/" + e.getId()) - 1
А почему такая проверка на то что меньше 2 и какие-то вычитания?

2023-02-15 19:33 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                    views.get("/events/" + e.getId()) == null ?
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Map.html#getOrDefault(java.lang.Object,V) будет как-то лучше смотреться

2023-02-15 19:33 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        StringBuilder uris = new StringBuilder();
Отличие от соседнего метода только в том. как получается список айдишников и как выставляются значения? может попробовать вынести какие-то вспомогательные методы, чтобы сократить дублирование?

2023-02-15 19:33 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +    // Циклическая зависимость eventServiceImpl <-> requestServiceImpl. Здесь нужен
Именно поэтому лучше ставить зависимости на репозитории, а не сервисы. Метод подсчета количества подтвержденных заявок может быть и в сервисе событий

2023-02-15 19:33 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +    RequestServiceImpl(RequestRepository requestRepository,
Модификатор доступа потерялся

2023-02-15 19:33 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +    public Map<Long, Long> countConfirmedRequests(List<Long> eventsId) {
Вот этот метод вполне может быть в сервисе событий

2023-02-15 21:07 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/enums/EventState.java
> +    public final String name;
Скорректировал

2023-02-15 21:10 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/model/Event.java
>      private List<Compilation> compilations;
@alexache Вопрос не совсем понятен.
Поле используется, как ему не использоваться. Это же подборки событий. Множество событий к множеству подборок. 
Ну и в постмане отдельная директория для проверки подборок.
Или я не так понял вопрос?

2023-02-15 21:29 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/model/Event.java
>      private List<Compilation> compilations;
@alexache Само поле напрямую не используется на стороне событий.
Оно нужно для обеспечения связи многие ко многим (множество событий к множеству подборок событий).

2023-02-15 21:32 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                            views.get("/events/" + e.getId()) : views.get("/events/" + e.getId()) - 1
Поправил. Была своя логика.

2023-02-15 21:37 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                    views.get("/events/" + e.getId()) == null ?
Красиво. Поправил.

2023-02-15 21:52 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +        StringBuilder uris = new StringBuilder();
Переделал через интерфейс. Теперь красиво.

2023-02-15 21:59 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +    public Map<Long, Long> countConfirmedRequests(List<Long> eventsId) {
Перенес. Ушла циклическая зависимость. Спасибо!

2023-02-15 21:59 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +    RequestServiceImpl(RequestRepository requestRepository,
Переделано

2023-02-15 22:00 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/request/service/RequestServiceImpl.java
> +    // Циклическая зависимость eventServiceImpl <-> requestServiceImpl. Здесь нужен
В последствии буду больше внимания уделять использованию репозиториев вместо сервисов.

2023-02-16 21:03 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/model/Event.java
>      private List<Compilation> compilations;
Сделал связь однонаправленной.

2023-02-16 23:54 UTC, alexache requested changes

2023-02-16 23:54 UTC, alexache commented on afisha-app/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                    views.getOrDefault(views.get("/events/" + e.getId()), 0L)
что-то здесь не то. Почему и getOrDefault и get? то есть сначала берется по ключу = получаем либо значение либо null, а затем считаем это ключом и ищем по нему?

2023-02-17 06:39 UTC, VitalyKapustin-git commented on afisha-app/src/main/java/ru/practicum/event/service/EventServiceImpl.java
> +                    views.getOrDefault(views.get("/events/" + e.getId()), 0L)
Поправил дублирование

2023-02-17 09:10 UTC, alexache approved these changes

2023-02-17 17:17 UTC, VitalyKapustin-git commented
Реализован сервис афиша

2023-02-17 17:18 UTC, merged